###################################################################
#  Makefile for project 2
#
#  Daniel R. Reynolds
#  SMU Mathematics
#  Math 3316
#  16 September 2013
###################################################################

# makefile targets
demo.exe : demo.cpp bisection.cpp newton.cpp secant.cpp
	g++ $^ -o $@

clean :
	\rm -f *.o *.txt

realclean : clean
	\rm -f *.exe *~


####### End of Makefile #######
